vitessce/wrappers.py

I think we should manage the _base_url in the abstract class rather than adding it to each child class individually

Manage base_url in the abstract class

---

tests/test_wrappers.py
vitessce/wrappers.py

This PR makes some formerly private methods publicand allows for a base url for configs and base filepath for zarr expression matrix.  This will allow us to build view configs more easily in HuBMAP as well as convert data using a "public api."  For example, for gene expression processing `create_exp_matrix_zarr` is likely needed to output the data since it will not be a straight usage of AnnData even once we have the loaders for `AnnData` completed.

Make Wrapper Methods Public and Add Base URL

---

docs/notebooks/widget_brain.ipynb
docs/notebooks/widget_loom.ipynb
docs/notebooks/widget_pbmc.ipynb
docs/notebooks/widget_pbmc_remote.ipynb
docs/notebooks/widget_shortcut.ipynb
docs/widget_examples.rst
tests/test_wrappers.py
vitessce/config.py
vitessce/constants.py
vitessce/export.py
vitessce/wrappers.py

Here we use Zarr for AnnData, supporting both local anndata objects and remote (zarr) stores. This breaks the current loom example because of a string parsing issue but I have opened an issue in [AnnData](https://github.com/theislab/anndata/issues/491) to make some progress on that.  In the meantime, I am going to clean this up and hopefully get a fix in for that issue so that the client can parse the loom object converted to anndata.

Zarr for AnnData 

---

docs/notebooks/widget_imaging.ipynb
js/package-lock.json
js/package.json
tests/test_config.py
tests/test_wrappers.py
vitessce/__init__.py
vitessce/config.py
vitessce/export.py
vitessce/routes.py
vitessce/widget.py
vitessce/wrappers.py

In this PR, I get rid of `on_obj` call back for `to_dict` on the view config object and internalize it by creating a new method on the configuration class, `get_routes`, to handle the behavior that `on_obj` seems to be used for repeatedly.
In the portal, we want to be able to call `to_dict` without any arguments and get the view config with the URLs from the wrappers/files.  In the current setup `to_dict` returns a view config with empty `files` field because it has no way of constructing the URLs with the `on_obj` callback.  The only catch with this method is that for local data, if you do not pass in a `base_url`, you could get back out a view config with completely unusable urls (as opposed to before, where `files` would just be empty).

Change on_obj Function + Upgrade Vitessce

---

vitessce/config.py

It was not clear to me that `layout` and explicitly setting the `x`, `w`, `h` and/or `y` were mutually exclusive - for example I thought you could set `h` or `w` and then we would "take care of the rest."  I just wanted to update the docs about that.

Update Docs for Layout

---

js/lib/widget.css
js/lib/widget.js

This PR fixes the issue of `<select` element heights being too small. It goes along with the checkbox height issue and the classic notebook interface font sizing issue.

Fix select css

---

.github/workflows/test.yml
environment.yml
vitessce/wrappers.py

bringing in pytest because the built-in doctest runner only works on individual files, and has problems with the paths.

Use pytest to run doctests

---

docs/notebooks/widget_imaging_segmentation.ipynb
js/package-lock.json
js/package.json
tests/test_wrappers.py
vitessce/_version.py
vitessce/wrappers.py

This PR:
- Adds the bitmask option to our Python API
- Fix some small documentation issues
- Add the other IMS image to the remote imaging notebook
- Make a bitmask notebook (we can delete this if you want @keller-mark it was mostly for my testing but figured I'd leave it in if we want to use it)
- Bumps the version of this package for release

Upgrade Vitessce to v1.1.10

---

CHANGELOG.md
docs/notebooks/web_app_brain.ipynb
vitessce/config.py
vitessce/widget.py

This PR adds an internal function `launch_vitessce_io` and a method `.web_app` on config instances. I factored out the shared data serving code from `VitessceWidget.__init__()` into two new internal functions `get_port_and_routes` and `serve_routes`.
The `web_app` method allows serving a config's data using the Starlette web server, but instead of rendering a widget, it creates a vitessce.io URL which includes the URLs of the served data. The new `web_app_brain.ipynb` notebook has a demo.

Added web_app method

---

setup.py

explain aiofiles dependency

---

setup.cfg

This PR adds a list of directories to exclude from flake8 (auto-generated ones like .ipynb_checkpoints and node_modules).
Without these excludes, the flake8 output looks like
[flake.txt](https://github.com/vitessce/vitessce-python/files/8490531/flake.txt)

Exclude directories from flake8 linting

---

environment.yml
setup.py

The PR #149 did fix #148 but now has a different error: the `build` dependency was not included in the `dev` extras_require https://github.com/vitessce/vitessce-python/runs/6211731831?check_suite_focus=true

Add build dependency

---

.github/workflows/lint.yml
setup.py

This ensures that CI is installing the same version a developer will install. (Initially, I thought about simplifying by getting rid of the extra, but then thought better of it.)

install flake8 from extras

---

vitessce/__init__.py

- Fix #167
Making the logic depend on the exact version number was my mistake: We want the same behavior (graceful fallback if optional deps not available) under every version of python.

Remove version-specific logic

---

CHANGELOG.md
setup.py
vitessce/_version.py

The release of ipywidgets 8.0.0 caused the change in behavior upon installing the vitessce package.

Pin ipywidgets dependency version

---

.github/workflows/deploy.yml

The GH_TOKEN seems to have broke when I replaced the previous blanket-permissions GitHub API token with a fine-grained API token after getting a message that my previous token was compromised from GitHub.
The previous github pages deployment action is now archived. https://github.com/alex-page/blazing-fast-gh-pages-deploy
This new https://github.com/actions/deploy-pages does not seem to need an API token so hopefully this works

Try to fix github pages deployment

---

.github/workflows/test_demos.yml
demos/dryrun_environment.yml

The demos environment takes hours to solve via conda/mamba https://github.com/conda-incubator/setup-miniconda/issues/196#issuecomment-1376320682
This PR sets up a minimal environment with only the dependencies needed to run the snakemake dryrun in the GitHub action. Not an ideal solution but seems to work.

Create smaller easier-to-solve CI env

---

README.md
setup.py
vitessce/config.py
vitessce/widget.py

As another fallback after `.widget` and `.web_app`, this adds `.display` to render Vitessce with only unidirectional communication in the notebook using the ipython display HTML function.

Add VitessceConfig.display

---

vitessce/widget.py

Fixes issue with dynamic JS `await import()` which is used by Viv internals/dependencies for loading OME-TIFF

Upgrade dynamic-import package version to fix bug

---

tests/create_test_data.py
tests/test_wrappers.py
vitessce/wrappers.py

This PR adds support and tests for the `obs_labels_names` and `obs_labels_paths` props for the AnndataWrapper to allow passing more than one set of obs labels and corresponding display names. I kept the legacy `obs_labels_path` prop in place but indicated it is deprecated.

NickAkhmetov/Add support for `obs_labels_names` and `obs_labels_paths` arrays

---

vitessce/constants.py

This PR adds two `coordinationValue` enum values listed in [vitessce docs](http://vitessce.io/docs/coordination-types/) which were not present in the Python enum class; it also adds the FileType values corresponding to `obs[segmentations/labels/locations/embedding].cells.json`.
Since the `metaCoordinationScopes`/`metaCoordinationScopesBy` coordination types are not fully documented, I did not add those entries, but can add them if desired.

NickAkhmetov/Update `CoordinationType` and `FileType` to match docs

---

vitessce/config.py

Fixes #271 
This PR allows for multiple coordination scopes of a single type to be used by a single view. This allows e.g. the use of multiple `obsLabelsType` coordinations at once.

NickAkhmetov/Add `allow_multiple_scopes_per_type` boolean arg to `use_coordination` and `link_views`

---

CHANGELOG.md
README.md
pyproject.toml

This PR bumps the package version to 3.0.7
I updated the CHANGELOG.md to include this version (though it's not very complete right now, I figured it wouldn't hurt to pick that habit back up)
I also updated the `README.md` to point to the correct file (since the package version is indicated in `pyproject.toml` not `setup.py`)

Release 3.0.7

---

pyproject.toml
tests/test_anndata_utils.py
vitessce/config.py
vitessce/widget.py
vitessce/wrappers.py

This change enables using the Vitessce widget in HPC situations, on Google Colab, in VSCode, and in HuBMAP Workspaces with data that is local to the Python kernel. Uses the new API from https://github.com/manzt/anywidget/pull/453
In these environments it can be difficult / impossible to proxy the requests from the browser in which the notebook is running down to the server on which the python kernel is running. Jupyter-server-proxy can only get us so far. Similarly, this may also fix #255 because this is another environment that presents challenges (e.g., it is not a web browser so we cannot rely on the structure of the notebook URL to help us construct the data URLs).
TODO:
One question is how to expose this in the API. Maybe we require the user to pass the store? Like
```diff
dataset = …
```

Use anywidget-based IPC for zarr gets which do not require serving data on localhost

---

pyproject.toml

`numpy` 2.0 released yesterday: https://numpy.org/doc/stable/reference/index.html
Since pip resolves to the latest supported version during install, this leads to a conflict with `ome`/`skimage`:
```
[2024-06-17 12:29:14] ERROR in hubmap_translator:835: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
[2024-06-17 12:29:14] ERROR in hubmap_translator:837: Failed to dynamically import transform module index: portal at time: 1718627354.2877655
Traceback (most recent call last):
File "/usr/src/app/src/hubmap_translator.py", line 832, in init_transformers
m = importlib.import_module(xform_module)
File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level) …
```

NickAkhmetov/Cap `numpy` under v2

---

pyproject.toml
tests/test_config.py
vitessce/config.py

This PR:
- Updates `VitessceConfig.from_dict()` to avoid losing the `requestInit` data for datasets' files
- Updates `VitessceConfigDatasetFile` to support initial `requestInit` configuration.
- Updates `VitessceConfigDataset.add_file` to support initial `requestInit` configurations.

NickAkhmetov/Copy `requestInit` when using `from_dict`

---

.coveragerc_omit
.github/workflows/test.yml
docs/notebooks/widget_plugin_custom.ipynb
docs/notebooks/widget_plugin_demo.ipynb
pyproject.toml
vitessce/__init__.py
vitessce/widget.py
vitessce/widget_plugins/__init__.py
vitessce/widget_plugins/demo_plugin.py

Fixes #347 
TODO:
- ensure `VitessceConfig.add_view` allows adding plugin views with names it does not know about
- allow for `VitessceConfig.add_view` to add view that lacks a `dataset` or `dataset_uid`?
- document new plugin class API / usage
- add example notebook using `DemoPlugin` class
- add test(s) for plugin API and the added VitessceWidget functionality

Plugin class

---

pyproject.toml
vitessce/widget.py

I was incorrect, the signature of the `invoke` function is `invoke(name, params, options = { buffers, signal })`. (For some reason I thought the third parameter was `buffers` and the fourth was `options`)
cc @EricMoerthVis

Fix invoke bug

---

tests/test_config_updates.py
vitessce/config.py

This PR adds functions `get_views()`, `get_view_by()`, and `remove_view_by` to update or remove a view from the ConfigView.
Addresses #104

Added utility functions to update and remove a view

---

pyproject.toml
tests/test_wrappers.py
vitessce/__init__.py
vitessce/wrappers.py

Add JsonWrapper class

---

README.md
pyproject.toml

Removes notes about conda environments and bumps version

Update pyproject yml and readme

---

docs/api_config.rst
docs/api_data.rst
docs/notebooks/marimo.py
docs/notebooks/spatial_data_visium_hd.ipynb
pyproject.toml
src/vitessce/config.py
src/vitessce/widget.py

Depends on https://github.com/vitessce/vitessce/pull/2216

Add Visium HD nb

---

pyproject.toml
src/vitessce/config.py
src/vitessce/widget.py

This is needed so that the Uvicorn server `host` parameter can be specified as `0.0.0.0` on HuBMAP workspaces

Add server_host param
