vitessce/vitessce-python

docs/notebooks/widget_brain.ipynb
=> Fix the number in widget_brain.ipynb

docs/conf.py, docs/getting_started.rst, docs/notebooks/data_conversion.ipynb, docs/notebooks/data_export_files.ipynb, docs/notebooks/data_export_s3.ipynb, docs/notebooks/widget_loom.ipynb, docs/widget_examples.rst, tests/test_wrappers.py, vitessce/__init__.py, vitessce/_version.py, vitessce/config.py, vitessce/wrappers.py
=> Minor tweaks to support Loom X,Y coordinates with AnnDataWrapper

docs/notebooks/widget_imaging.ipynb
Forgot these are in the docs pages, so this adds some documentation of where I got the data/what is going on.
=> Add Descriptions to Imaging Notebooks.

vitessce/_version.py
Needed for https://github.com/hubmapconsortium/portal-ui/pull/1581
=> Bump Version to 0.1.8alpha

README.md
=> Add note about conda environments

docs/notebooks/data_conversion.ipynb, docs/notebooks/data_export_files.ipynb, docs/notebooks/data_export_s3.ipynb, docs/notebooks/widget_brain.ipynb, docs/notebooks/widget_from_dict.ipynb, docs/notebooks/widget_genomic_profiles.ipynb, docs/notebooks/widget_loom.ipynb, docs/notebooks/widget_pbmc.ipynb, docs/notebooks/widget_pbmc_remote.ipynb, docs/notebooks/widget_shortcut.ipynb
When I save a notebook, I'm getting these version bumps... ok to bump these all up for consistency?
=> bump versions on all notebooks

js/package-lock.json, js/package.json, tests/test_config.py, vitessce/_version.py, vitessce/config.py
Following up on https://github.com/vitessce/vitessce/pull/1001 here
=> Upgrade Vitessce and View config for 3D Fix

docs/notebooks/data_export_s3.ipynb
Found here: https://github.com/vitessce/vitessce-python/issues/88#issuecomment-888380914
=> Fix Export Example `mapping` Prop

vitessce/constants.py
They both should be deprecated? Let me know.
=> Add `clusters.json` and `genes.json`

CHANGELOG.md
This upgrades Vitessce to 1.1.13 necessitating the addition of the `disableChannelsIfRgbDetected` prop from https://github.com/vitessce/vitessce/pull/1015
=> Upgrade Vitessce to 1.1.13

vitessce/config.py
=> Get dataset function

.gitignore, MANIFEST.in, README.md, environment.yml, install.json, js/package-lock.json, js/package.json, js/webpack.config.js, pyproject.toml, setup.py, vitessce/__init__.py, vitessce/_version.py
Fixes #29
Fixes #36 
Uses latest ipywidget cookiecutter template from https://github.com/jupyter-widgets/widget-cookiecutter/tree/9694718
=> Release 1.0.0

binder/environment.yml, docs/notebooks/environment.yml, environment.yml
=> Pin anndata versions

setup.py
=> Use README on Pypi

.github/workflows/deploy.yml, .github/workflows/test_js.yml
=> Try fixing deploy github action

.github/workflows/deploy.yml, setup.py
=> Try to fix deploy again

js/package-lock.json, js/package.json, tests/test_config.py, vitessce/_version.py, vitessce/config.py, vitessce/wrappers.py
Towards https://github.com/hubmapconsortium/portal-ui/issues/2393
=> Vitessce 1.1.20

.github/workflows/deploy.yml, README.md, docs/conf.py
Fixes #169 , related to https://github.com/vitessce/vitessce/pull/1251
=> Rename default branch

js/package-lock.json, js/package.json, setup.py, vitessce/wrappers.py
=> Vitessce 1.2.2

docs/data_examples.rst, docs/notebooks/widget_brain_with_base_dir.ipynb, tests/test_config.py, tests/test_wrappers.py, vitessce/config.py, vitessce/wrappers.py
=> base_dir mode

vitessce/wrappers.py
This is needed to allow providing molecules via AnnData (at least in the current state of the vitessce JS)
=> Add support for obsLabels with AnnData

vitessce/wrappers.py
=> Add file extensions

.github/workflows/test_demos.yml, pyproject.toml, tests/test_ome_utils.py, vitessce/data_utils/ome.py
Two unrelated issues encountered:
- https://github.com/snakemake/snakemake/issues/2607
- https://github.com/sphinx-doc/sphinx/issues/11130
=> Upgrade ome-zarr package

vitessce/wrappers.py
=> Support obsSpots and obsPoints

.coveragerc_omit, pyproject.toml, tests/test_config.py, vitessce/__init__.py, vitessce/config.py, vitessce/utils.py
This PR adds the optional parameter `scope_prefix` to the VitessceConfig.link_views_by_dict function. This was added on the JS side in https://github.com/vitessce/vitessce/commit/6dc0e1ad0c88c55cac9fb38c8666fea5e578984e
=> Support scope_prefix parameter in link_views_by_dict

pyproject.toml, tests/test_anndata_utils.py, vitessce/widget.py
=> Versions of anndata, anywidget, JS package

vitessce/wrappers.py
This PR:
- Moves the `request_init` param from the `AnndataWrapper` to the `AbstractWrapper`
- Adds support for the `request_init` param to the `MultivecZarrWrapper`
This change allows for the `requestInit` dict to be passed to genomic profiles views.
=> NickAkhmetov/Add `requestInit` param to `MultivecZarrWrapper`

pyproject.toml
Minor patch to add `requestInit` param support to the multivec zarr wrapper.
=> Release v3.2.5

docs/data_options.rst, docs/index.rst, docs/widget_plugins.rst, pyproject.toml, setup.cfg, vitessce/widget.py, vitessce/widget_plugins/__init__.py, vitessce/widget_plugins/demo_plugin.py, vitessce/wrappers.py
Fixes https://github.com/vitessce/vitessce-python/issues/334
=> Create module for plugin JS

docs/notebooks/widget_pbmc.ipynb, pyproject.toml, vitessce/widget.py
=> Fix binder example

pyproject.toml, vitessce/widget.py
Depends on https://github.com/vitessce/vitessce/pull/1942
=> Keller mark/more exports

docs/notebooks/spatial_data.ipynb
Fixes https://github.com/vitessce/vitessce-python/issues/395
=> Fix spatialdata configuration

README.md, pyproject.toml, src/vitessce/widget.py
This PR updates the url in the options object for files.
=> Updated url for options object

pyproject.toml, src/vitessce/responses.py, src/vitessce/widget.py, src/vitessce/wrappers.py, uv.lock
- Remove upper limit for `anndata`, Fixes #434 
- Remove upper limit for `starlette` and add `styleContainer` widget prop, Fixes #431 
- Add `spatialdata` to an extras-require section, Towards #428
=> Upgrade/loosen dependencies and add invoke_batched parameter

docs/notebooks/marimo.py, docs/notebooks/widget_neuroglancer.ipynb, pyproject.toml, src/vitessce/widget.py
Depends on https://github.com/vitessce/vitessce/pull/2130
=> Notebook which demonstrates neuroglancer view

pyproject.toml, src/vitessce/__init__.py, src/vitessce/widget.py, tests/test_config_converter.py
=> Limit dependencies

pyproject.toml, src/vitessce/constants.py, src/vitessce/widget.py, src/vitessce/wrappers.py
This PR updates the JS version as well as adds support for zipped spatialData objects.
=> Updated version and added zip support
